### ISSUE TITLE
Generating two files without closing the randomizer first makes the second file unplayale.

### ISSUE THREAD

**Issue by GigaOtomia** [TokyoScarab/MMX-Randomizer#35]
Self-explanatory. Provided is an example of this in effect - this is the second file generated after choosing a bunch of options.
[Friday In '88.zip](https://github.com/TokyoScarab/MMX-Randomizer/files/1997403/Friday.In.88.zip)

**Comment by TokyoScarab** [comment]
This has since been fixed.  I had caught it not too long after I put the update out for it.
