### ISSUE TITLE
Release the actual source code.

### ISSUE THREAD

**Issue by wolfman2000** [TokyoScarab/MMX-Randomizer#42]
Github is meant to host source code, not applications. I have not seen any actual code that one can review and make pull requests for.

Please release the source to this randomizer.

**Comment by TokyoScarab** [comment]
Hello.  First off, no it's not.  Github is not for only hosting source code.  This is never stated anywhere in their ToS nor is there anything mentioned about intended project hosting protocols or how they would like the site to be used in relation to software hosting.  Github has always been about a place for a person or group of people to publicly host and work on projects together.  I'm not the first, nor will I be the last person to use this site for hosting their projects.  The audacity and tone of this comment is just appalling.  This is my project, not yours.  You don't have any right to come in here and just start making demands about me forking over this and that.  If I wanted this project to be open source, I would have made it that way from the start.  There is a community involvement as far as giving me bug feedback and ideas for future improvements.  This is how this project can evolve and Github is the ideal place for it, and quite frankly, if you can't accept that, I politely implore you to please fuck off.
